us = [{'name': 'Alabama', 'abbreviation': 'AL', 'country': 'United States', 'country_short': 'US'}, {'name': 'Alaska', 'abbreviation': 'AK', 'country':
'United States', 'country_short': 'US'}, {'name': 'American Samoa', 'abbreviation': 'AS', 'country': 'United States', 'country_short': 'US'}, {'name': 'Arizona', 'abbreviation': 'AZ', 'country': 'United States', 'country_short': 'US'}, {'name': 'Arkansas', 'abbreviation': 'AR', 'country': 'United States', 'country_short': 'US'}, {'name': 'California', 'abbreviation': 'CA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Colorado', 'abbreviation': 'CO', 'country': 'United States', 'country_short': 'US'}, {'name': 'Connecticut', 'abbreviation': 'CT', 'country': 'United States', 'country_short': 'US'}, {'name': 'Delaware', 'abbreviation': 'DE', 'country': 'United States', 'country_short': 'US'}, {'name': 'District of Columbia', 'abbreviation': 'DC', 'country': 'United States', 'country_short': 'US'}, {'name': 'Federated States Of Micronesia', 'abbreviation': 'FM', 'country': 'United States', 'country_short': 'US'}, {'name': 'Florida', 'abbreviation': 'FL', 'country': 'United States', 'country_short': 'US'}, {'name': 'Georgia', 'abbreviation': 'GA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Guam', 'abbreviation': 'GU', 'country': 'United States', 'country_short': 'US'}, {'name': 'Hawaii', 'abbreviation': 'HI', 'country': 'United States', 'country_short': 'US'}, {'name': 'Idaho', 'abbreviation': 'ID', 'country': 'United States', 'country_short': 'US'}, {'name': 'Illinois', 'abbreviation': 'IL', 'country': 'United States', 'country_short': 'US'}, {'name': 'Indiana', 'abbreviation': 'IN', 'country': 'United States', 'country_short': 'US'}, {'name': 'Iowa', 'abbreviation': 'IA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Kansas', 'abbreviation': 'KS', 'country': 'United States', 'country_short': 'US'}, {'name': 'Kentucky', 'abbreviation': 'KY', 'country': 'United States', 'country_short': 'US'}, {'name': 'Louisiana', 'abbreviation': 'LA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Maine', 'abbreviation': 'ME', 'country': 'United States', 'country_short': 'US'}, {'name': 'Marshall Islands', 'abbreviation': 'MH', 'country': 'United States', 'country_short': 'US'}, {'name': 'Maryland', 'abbreviation': 'MD', 'country': 'United States', 'country_short': 'US'}, {'name': 'Massachusetts', 'abbreviation': 'MA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Michigan', 'abbreviation': 'MI', 'country': 'United States', 'country_short': 'US'}, {'name': 'Minnesota', 'abbreviation': 'MN', 'country': 'United States', 'country_short': 'US'}, {'name': 'Mississippi', 'abbreviation': 'MS', 'country': 'United States', 'country_short': 'US'}, {'name': 'Missouri', 'abbreviation': 'MO', 'country': 'United States', 'country_short': 'US'}, {'name': 'Montana', 'abbreviation': 'MT', 'country': 'United States', 'country_short': 'US'}, {'name': 'Nebraska', 'abbreviation': 'NE', 'country': 'United States', 'country_short': 'US'}, {'name':
'Nevada', 'abbreviation': 'NV', 'country': 'United States', 'country_short': 'US'}, {'name': 'New Hampshire', 'abbreviation': 'NH', 'country': 'United States', 'country_short': 'US'}, {'name': 'New Jersey', 'abbreviation': 'NJ', 'country': 'United States', 'country_short': 'US'}, {'name': 'New Mexico', 'abbreviation': 'NM', 'country': 'United States', 'country_short': 'US'}, {'name': 'New York', 'abbreviation': 'NY', 'country': 'United States', 'country_short': 'US'}, {'name': 'North Carolina', 'abbreviation': 'NC', 'country': 'United States', 'country_short': 'US'}, {'name': 'North Dakota', 'abbreviation': 'ND', 'country': 'United States', 'country_short': 'US'}, {'name': 'Northern Mariana Islands', 'abbreviation': 'MP', 'country': 'United States', 'country_short': 'US'}, {'name': 'Ohio', 'abbreviation': 'OH', 'country': 'United States', 'country_short': 'US'}, {'name': 'Oklahoma', 'abbreviation': 'OK', 'country': 'United States', 'country_short': 'US'}, {'name': 'Oregon', 'abbreviation': 'OR', 'country': 'United States', 'country_short': 'US'}, {'name': 'Palau', 'abbreviation': 'PW', 'country': 'United States', 'country_short': 'US'}, {'name': 'Pennsylvania', 'abbreviation': 'PA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Puerto Rico', 'abbreviation': 'PR', 'country': 'United States', 'country_short': 'US'}, {'name': 'Rhode Island', 'abbreviation': 'RI', 'country': 'United States', 'country_short': 'US'}, {'name': 'South Carolina', 'abbreviation': 'SC', 'country': 'United States', 'country_short': 'US'}, {'name': 'South Dakota', 'abbreviation': 'SD', 'country': 'United States', 'country_short': 'US'}, {'name': 'Tennessee', 'abbreviation': 'TN', 'country': 'United States', 'country_short': 'US'}, {'name': 'Texas', 'abbreviation': 'TX', 'country': 'United States', 'country_short': 'US'}, {'name': 'Utah', 'abbreviation': 'UT', 'country': 'United States', 'country_short': 'US'}, {'name': 'Vermont', 'abbreviation': 'VT', 'country': 'United States', 'country_short': 'US'}, {'name': 'Virgin Islands', 'abbreviation': 'VI', 'country': 'United States', 'country_short': 'US'}, {'name': 'Virginia', 'abbreviation': 'VA', 'country': 'United States', 'country_short': 'US'}, {'name': 'Washington', 'abbreviation': 'WA', 'country': 'United States', 'country_short': 'US'}, {'name': 'West Virginia', 'abbreviation': 'WV', 'country': 'United States', 'country_short': 'US'}, {'name': 'Wisconsin', 'abbreviation': 'WI', 'country': 'United States', 'country_short': 'US'}, {'name': 'Wyoming', 'abbreviation': 'WY', 'country': 'United States', 'country_short': 'US'}]

ca = [
    {
        'name': 'Alberta',
        'abbreviation': 'AB',
        'country': 'Canada',
        'country_short': 'CA'
    },
    {
        'name': 'British Columbia',
        'abbreviation': 'BC',
        'country': 'Canada',
        'country_short': 'CA'
    }, {'name': 'Manitoba', 'abbreviation': 'MB', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'New Brunswick', 'abbreviation': 'NB', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Newfoundland and Labrador', 'abbreviation': 'NL', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Northwest Territories', 'abbreviation': 'NT', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Nova Scotia', 'abbreviation': 'NS', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Nunavut', 'abbreviation': 'NU', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Ontario', 'abbreviation': 'ON', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Prince Edward Island', 'abbreviation': 'PE', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Quebec', 'abbreviation': 'QC', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Saskatchewan', 'abbreviation': 'SK', 'country': 'Canada', 'country_short': 'CA'}, {'name': 'Yukon Territory', 'abbreviation': 'YT', 'country': 'Canada', 'country_short': 'CA'}]

uk = [
    {
    'name': 'Avon',
    'abbreviation': 'AVN',
    'country': 'England',
    'country_short': 'UK'
    },
{
    'name': 'Bedfordshire',
    'abbreviation': 'BDF',
    'country': 'England',
    'country_short': 'UK'},
{'name': 'Berkshire', 'abbreviation': 'BRK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Buckinghamshire', 'abbreviation': 'BKM', 'country': 'England', 'country_short': 'UK'}, {'name': 'Cambridgeshire', 'abbreviation': 'CAM', 'country': 'England',
'country_short': 'UK'}, {'name': 'Cheshire', 'abbreviation': 'CHS', 'country': 'England', 'country_short': 'UK'}, {'name': 'Cleveland', 'abbreviation': 'CLV', 'country': 'England', 'country_short': 'UK'}, {'name': 'Cornwall', 'abbreviation': 'CON', 'country': 'England', 'country_short': 'UK'}, {'name': 'Cumbria', 'abbreviation': 'CMA', 'country': 'England', 'country_short': 'UK'}, {'name': 'Derbyshire', 'abbreviation': 'DBY', 'country':
'England', 'country_short': 'UK'}, {'name': 'Devon', 'abbreviation': 'DEV', 'country': 'England', 'country_short': 'UK'}, {'name': 'Dorset', 'abbreviation': 'DOR', 'country': 'England', 'country_short': 'UK'}, {'name': 'Durham', 'abbreviation': 'DUR', 'country': 'England', 'country_short': 'UK'}, {'name': 'East Sussex', 'abbreviation': 'SXE', 'country': 'England', 'country_short': 'UK'}, {'name': 'Essex', 'abbreviation': 'ESS', 'country': 'England', 'country_short': 'UK'}, {'name': 'Gloucestershire', 'abbreviation': 'GLS', 'country': 'England', 'country_short': 'UK'}, {'name': 'Hampshire', 'abbreviation': 'HAM', 'country': 'England', 'country_short': 'UK'}, {'name': 'Herefordshire', 'abbreviation': 'HEF', 'country': 'England', 'country_short': 'UK'}, {'name': 'Hertfordshire', 'abbreviation': 'HRT', 'country': 'England', 'country_short': 'UK'}, {'name': 'Isle of Wight',
'abbreviation': 'IOW', 'country': 'England', 'country_short': 'UK'}, {'name': 'Kent', 'abbreviation': 'KEN', 'country': 'England', 'country_short': 'UK'}, {'name': 'Lancashire', 'abbreviation': 'LAN', 'country': 'England', 'country_short': 'UK'}, {'name': 'Leicestershire', 'abbreviation': 'LEI', 'country': 'England', 'country_short': 'UK'}, {'name': 'Lincolnshire', 'abbreviation': 'LIN', 'country': 'England', 'country_short': 'UK'}, {'name': 'London', 'abbreviation': 'LDN', 'country': 'England', 'country_short': 'UK'}, {'name': 'Merseyside', 'abbreviation': 'MSY', 'country': 'England', 'country_short': 'UK'}, {'name': 'Norfolk', 'abbreviation': 'NFK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Northamptonshire',
'abbreviation': 'NTH', 'country': 'England', 'country_short': 'UK'}, {'name': 'Northumberland', 'abbreviation': 'NBL', 'country': 'England', 'country_short': 'UK'}, {'name': 'North Yorkshire', 'abbreviation': 'NYK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Nottinghamshire', 'abbreviation': 'NTT', 'country': 'England', 'country_short': 'UK'}, {'name': 'Oxfordshire', 'abbreviation': 'OXF', 'country': 'England', 'country_short': 'UK'}, {'name': 'Rutland', 'abbreviation': 'RUT', 'country': 'England', 'country_short': 'UK'}, {'name': 'Shropshire', 'abbreviation': 'SAL', 'country': 'England', 'country_short': 'UK'}, {'name': 'Somerset', 'abbreviation': 'SOM', 'country': 'England', 'country_short': 'UK'}, {'name': 'South Yorkshire', 'abbreviation': 'SYK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Staffordshire', 'abbreviation': 'STS', 'country': 'England', 'country_short': 'UK'}, {'name': 'Suffolk', 'abbreviation': 'SFK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Surrey', 'abbreviation': 'SRY', 'country': 'England', 'country_short': 'UK'}, {'name': 'Tyne and Wear', 'abbreviation': 'TWR', 'country': 'England', 'country_short': 'UK'}, {'name': 'Warwickshire', 'abbreviation': 'WAR', 'country': 'England', 'country_short': 'UK'}, {'name': 'West Midlands', 'abbreviation':
'WMD', 'country': 'England', 'country_short': 'UK'}, {'name': 'West Sussex', 'abbreviation': 'SXW', 'country': 'England', 'country_short': 'UK'}, {'name': 'West Yorkshire', 'abbreviation': 'WYK', 'country': 'England', 'country_short': 'UK'}, {'name': 'Wiltshire', 'abbreviation': 'WIL', 'country': 'England', 'country_short': 'UK'}, {'name': 'Worcestershire', 'abbreviation': 'WOR', 'country': 'England', 'country_short': 'UK'}, {'name': 'Clwyd', 'abbreviation': 'CWD', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Dyfed', 'abbreviation': 'DFD', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Gwent', 'abbreviation': 'GNT', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Gwynedd', 'abbreviation': 'GWN', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Mid Glamorgan', 'abbreviation': 'MGM', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Powys',
'abbreviation': 'POW', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'South Glamorgan', 'abbreviation': 'SGM', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'West Glamorgan', 'abbreviation': 'WGM', 'country': 'Wales', 'country_short': 'UK'}, {'name': 'Aberdeenshire', 'abbreviation': 'ABD', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Angus', 'abbreviation': 'ANS', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Argyll', 'abbreviation': 'ARL', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Ayrshire', 'abbreviation': 'AYR', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Banffshire', 'abbreviation': 'BAN', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Berwickshire', 'abbreviation': 'BEW', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Bute', 'abbreviation': 'BUT', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Caithness', 'abbreviation': 'CAI', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Clackmannanshire', 'abbreviation': 'CLK', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Dumfriesshire', 'abbreviation': 'DGY', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Dunbartonshire', 'abbreviation': 'DNB', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'East Lothian', 'abbreviation': 'ELN', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Fife', 'abbreviation': 'FIF', 'country': 'Scotland', 'country_short': 'UK'}, {'name':
'Inverness-shire', 'abbreviation': 'INV', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Kincardineshire', 'abbreviation': 'KCD', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Kinross-shire', 'abbreviation': 'KRS', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Kirkcudbrightshire', 'abbreviation': 'KKD', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Lanarkshire', 'abbreviation': 'LKS', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Midlothian', 'abbreviation': 'MLN', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Moray', 'abbreviation': 'MOR', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Nairnshire', 'abbreviation': 'NAI', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Orkney', 'abbreviation': 'OKI', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Peeblesshire', 'abbreviation':
'PEE', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Perthshire', 'abbreviation': 'PER', 'country': 'Scotland', 'country_short': 'UK'},
{'name': 'Renfrewshire', 'abbreviation': 'RFW', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Ross-shire', 'abbreviation': 'ROC', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Roxburghshire', 'abbreviation': 'ROX', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Selkirkshire', 'abbreviation': 'SEL', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Shetland', 'abbreviation': 'SHI', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Stirlingshire', 'abbreviation': 'STI', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Sutherland', 'abbreviation': 'SUT', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'West Lothian', 'abbreviation': 'WLN', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Wigtownshire', 'abbreviation': 'WIG', 'country': 'Scotland', 'country_short': 'UK'}, {'name': 'Antrim', 'abbreviation': 'ANT', 'country': 'Northern Ireland', 'country_short': 'UK'}, {'name': 'Armagh', 'abbreviation': 'ARM', 'country': 'Northern Ireland', 'country_short': 'UK'}, {'name': 'Down', 'abbreviation': 'DOW', 'country': 'Northern Ireland', 'country_short': 'UK'}, {'name': 'Fermanagh', 'abbreviation':
'FER', 'country': 'Northern Ireland', 'country_short': 'UK'}, {'name': 'Londonderry', 'abbreviation': 'LDY', 'country': 'Northern Ireland', 'country_short': 'UK'}, {'name': 'Tyrone', 'abbreviation': 'TYR', 'country': 'Northern Ireland', 'country_short': 'UK'}]
