# Generated by Django 4.0.4 on 2023-08-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_delete_emailtemplate'),
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization_wide_email', models.IntegerField(help_text='100 maximum emails organization wide per 24hr')),
                ('email_per_project', models.IntegerField(help_text='At maximum 2 emails per project per 24hr')),
                ('email_per_contact', models.IntegerField(help_text='At maximum 1 email to contact per 24hr')),
                ('email_per_account', models.IntegerField(help_text='At maximum 6 emails per account per 24 hr period.')),
                ('template_per_project', models.IntegerField(help_text='Email template can be used at maximum 1 time per project per 24hr.')),
                ('template_per_contact', models.IntegerField(help_text='Can not send the same template back to back to a contact')),
                ('type', models.CharField(choices=[('GC', 'General Contractor'), ('PB', 'Project Board')], default='PB', max_length=2, null=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=3000, null=True)),
                ('email_type', models.CharField(choices=[('GC', 'General Contractor'), ('PB', 'Project Board')], max_length=2, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('subject', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('is_mass_email', models.BooleanField(default=False, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.companyaccount')),
                ('company_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.contact')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.contactrole')),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='projects.opportunity')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='email_templates.emailtemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_sent'],
                'get_latest_by': 'time_sent',
            },
        ),
    ]
