# Generated by Django 4.0.4 on 2023-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email_type',
            field=models.CharField(choices=[('GC', 'General Contractor'), ('PB', 'Project Board'), ('ME', 'Mass Email')], max_length=2, null=True),
        ),
    ]
