# Generated by Django 4.0.4 on 2022-08-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_company_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='file',
            new_name='file_url',
        ),
    ]
