# Generated by Django 4.0.4 on 2022-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
