# Generated by Django 4.0.4 on 2022-08-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='file_url',
            new_name='file',
        ),
    ]
