# Generated by Django 4.0.4 on 2022-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_file_url_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
