# Generated by Django 4.0.4 on 2022-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_userprofile_file_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
