# Generated by Django 4.0.4 on 2022-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userprofile_project_contact_1_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project_contact_1_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_contact_1_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_contact_1_phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_site_contact_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_site_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_site_contact_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
