# Generated by Django 4.0.4 on 2023-01-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_userprofile_project_contact_1_email_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='free_template_count',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
