# Generated by Django 4.0.4 on 2023-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_userprofile_customer_userprofile_free_template_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_mode_action',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
