# Generated by Django 4.0.4 on 2023-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_userprofile_free_mode_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_mode_action',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
