# Generated by Django 4.0.4 on 2023-08-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_userprofile_project_archives_and_more'),
    ]

    operations = [

    ]
