# Generated by Django 4.0.4 on 2023-08-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_userprofile_domain_verification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='domain_verification',
            new_name='is_domain_verify',
        ),
    ]
