# Generated by Django 4.0.4 on 2023-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_rename_domain_verification_userprofile_is_domain_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='outbound_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
