# Generated by Django 4.0.4 on 2023-08-24 14:20

from django.db import migrations


def update_profile(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    user = apps.get_model("authentication", "User")
    try:
        users = user.objects.all().prefetch_related("profile")
        for user in users:
            user.profile.outbound_email = user.email
            user.profile.save()
    except Exception as e:
        print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0023_userprofile_outbound_email'),
    ]

    operations = [
        migrations.RunPython(update_profile),
    ]
