# Generated by Django 4.0.4 on 2023-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_userprofile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLN', 'cleaner'), ('GC', 'general_contractor')], default='CLN', max_length=20),
        ),
    ]
