# Generated by Django 4.0.4 on 2023-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_opportunity_modified'),
        ('authentication', '0027_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_viewed',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_project_viewed', to='projects.opportunity'),
        ),
    ]
