# Generated by Django 4.0.4 on 2023-07-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcqualify', '0005_planroom_delete_companyaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanRoom',
        ),
    ]
