# Generated by Django 4.0.4 on 2023-07-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcqualify', '0007_planroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planroom',
            old_name='account',
            new_name='user_profile',
        ),
    ]
