# Generated by Django 4.0.4 on 2023-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcqualify', '0008_rename_account_planroom_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planroom',
            old_name='began_application_process',
            new_name='date_visited',
        ),
        migrations.RemoveField(
            model_name='planroom',
            name='confirm_on_bid_list',
        ),
        migrations.RemoveField(
            model_name='planroom',
            name='region',
        ),
    ]
