# Generated by Django 4.0.4 on 2023-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcqualify', '0009_rename_began_application_process_planroom_date_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planroom',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
