# Generated by Django 4.0.4 on 2022-12-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('rough', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fluff', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rough_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rough_fluff', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('final_fluff', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rough_final_fluff', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
