# Generated by Django 4.0.4 on 2022-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0002_statelaborprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statelaborprice',
            name='average_rate',
        ),
        migrations.AddField(
            model_name='statelaborprice',
            name='average_labor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='statelaborprice',
            name='one_day_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='statelaborprice',
            name='price_customer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='statelaborprice',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
