# Generated by Django 4.0.4 on 2023-01-10 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mortgage_calculator', '0003_remove_statelaborprice_average_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanUPEstimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('square_foot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('living_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_pricing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('phase', models.CharField(blank=True, max_length=100)),
                ('not_sure', models.IntegerField()),
                ('no_stories', models.IntegerField()),
                ('price_per1_bed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per2_bed', models.IntegerField()),
                ('no_stories_check', models.BooleanField(default=False)),
                ('no_of_unit1_bed', models.IntegerField()),
                ('no_of_unit2_bed', models.IntegerField()),
                ('no_of_unit3_bed', models.IntegerField()),
                ('use_unit_pricing', models.BooleanField(default=False)),
                ('scrubbing_pricing', models.BooleanField(default=False)),
                ('use_living_unit_pricing', models.BooleanField(default=False)),
                ('laborersOnSite', models.IntegerField()),
                ('hours_crew_works_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_labor_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_days_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_over_head', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_costs_over_head', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cleanup_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
