# Generated by Django 4.0.4 on 2023-01-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0005_alter_cleanupestimates_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanupestimates',
            name='project_type',
        ),
    ]
