# Generated by Django 4.0.4 on 2023-01-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0006_remove_cleanupestimates_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupestimates',
            name='laborersOnSite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit1_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit2_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit3_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_stories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_stories_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='not_sure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='price_per2_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='scrubbing_pricing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='use_living_unit_pricing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='use_unit_pricing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
