# Generated by Django 4.0.4 on 2023-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0011_remove_cleanupestimates_emergency_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupestimates',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
