# Generated by Django 4.0.4 on 2023-01-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0012_alter_cleanupestimates_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='emergency_pricing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
