# Generated by Django 4.0.4 on 2023-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0013_cleanupestimates_emergency_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_stories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
