# Generated by Django 4.0.4 on 2023-01-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0015_cleanupestimates_price_per3_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupestimates',
            name='emergency_pricing',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit1_bed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit2_bed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='no_of_unit3_bed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleanupestimates',
            name='not_sure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
