# Generated by Django 4.0.4 on 2023-01-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0016_alter_cleanupestimates_emergency_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupestimates',
            name='emergency_pricing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
