# Generated by Django 4.0.4 on 2023-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0017_alter_cleanupestimates_emergency_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
