# Generated by Django 4.0.4 on 2023-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0018_cleanupestimates_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='use_price_per_day',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
