# Generated by Django 4.0.4 on 2023-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0019_cleanupestimates_use_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='use_number_of_days',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
