# Generated by Django 4.0.4 on 2023-07-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0020_cleanupestimates_use_number_of_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanupestimates',
            old_name='no_of_days_expected',
            new_name='noOfDaysExpected',
        ),
    ]
