# Generated by Django 4.0.4 on 2023-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0021_rename_no_of_days_expected_cleanupestimates_noofdaysexpected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='pressure_wash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cleanupestimates',
            name='pressure_wash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cleanupestimates',
            name='price_per_window',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cleanupestimates',
            name='window_panes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
