# Generated by Django 4.0.4 on 2023-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0022_cleanupestimates_pressure_wash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanupestimates',
            name='pressure_wash_price',
        ),
        migrations.RemoveField(
            model_name='cleanupestimates',
            name='price_per_window',
        ),
    ]
