# Generated by Django 4.0.4 on 2023-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0023_remove_cleanupestimates_pressure_wash_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='pressure_wash_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cleanupestimates',
            name='price_per_window',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10, null=True),
        ),
    ]
