# Generated by Django 4.0.4 on 2023-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_calculator', '0024_cleanupestimates_pressure_wash_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupestimates',
            name='accurate_days_on_site',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cleanupestimates',
            name='use_accurate_days_on_site',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
