# Generated by Django 4.0.4 on 2023-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities_statement', '0002_alter_capability_statement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability_statement',
            name='version',
            field=models.CharField(default='version a', max_length=200),
            preserve_default=False,
        ),
    ]
