# Generated by Django 4.0.4 on 2023-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities_statement', '0003_capability_statement_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability_statement',
            name='core_competencies_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capability_statement',
            name='past_performance_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capability_statement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
