# Generated by Django 4.0.4 on 2023-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities_statement', '0004_alter_capability_statement_core_competencies_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability_statement',
            name='about_us_header',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capability_statement',
            name='core_competencies_header',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capability_statement',
            name='difference_header',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capability_statement',
            name='past_performance_header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
