# Generated by Django 4.0.4 on 2023-09-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities_statement', '0007_capability_statement_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability_statement',
            name='header_name',
            field=models.CharField(default='CAPABILITIES STATEMENT', max_length=100),
        ),
    ]
