# Generated by Django 4.0.4 on 2022-07-23 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_street', models.CharField(max_length=150)),
                ('project_city', models.CharField(blank=True, max_length=150, null=True)),
                ('project_state', models.CharField(blank=True, max_length=150, null=True)),
                ('project_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('project_type', models.CharField(max_length=150)),
                ('bid_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_1_name', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_1_email', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_1_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_2_name', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_2_email', models.CharField(blank=True, max_length=150, null=True)),
                ('project_contact_2_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_street', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(max_length=150)),
                ('company_street', models.CharField(blank=True, max_length=150, null=True)),
                ('company_state', models.CharField(blank=True, max_length=150, null=True)),
                ('company_city', models.CharField(blank=True, max_length=150, null=True)),
                ('company_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('company_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('company_contact_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
