# Generated by Django 4.0.4 on 2022-08-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_point_contact_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_point_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_point_contact_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
