# Generated by Django 4.0.4 on 2022-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_proposal_point_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='project_street',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
