# Generated by Django 4.0.4 on 2022-08-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_proposal_project_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ffile_url',
            field=models.URLField(null=True),
        ),
    ]
