# Generated by Django 4.0.4 on 2022-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_proposal_ffile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='job_site_contact_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job_site_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job_site_contact_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
