# Generated by Django 4.0.4 on 2022-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_proposal_job_site_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='company_state_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='current_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
