# Generated by Django 4.0.4 on 2022-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_alter_proposal_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
