# Generated by Django 4.0.4 on 2022-09-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_alter_proposal_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='project_type',
        ),
    ]
