# Generated by Django 4.0.4 on 2022-09-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0003_alter_projecttype_template'),
        ('proposal', '0009_remove_proposal_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_type_proposals', to='project_type.projecttype'),
        ),
    ]
