# Generated by Django 4.0.4 on 2022-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0003_alter_projecttype_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
