# Generated by Django 4.0.4 on 2023-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0004_projecttype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
