# Generated by Django 4.0.4 on 2023-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0005_alter_projecttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='temaplate_1',
            field=models.FileField(null=True, upload_to='project_type_upload/'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='temaplate_2',
            field=models.FileField(null=True, upload_to='project_type_upload/'),
        ),
    ]
