# Generated by Django 4.0.4 on 2023-06-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0008_alter_projecttype_template_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttype',
            old_name='template_1',
            new_name='template_A',
        ),
        migrations.RenameField(
            model_name='projecttype',
            old_name='template_2',
            new_name='template_B',
        ),
    ]
