# Generated by Django 4.0.4 on 2023-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0010_rename_template_a_projecttype_template_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='template_a',
            field=models.FileField(blank=True, null=True, upload_to='project_type_upload/fl_attachment'),
        ),
    ]
