# Generated by Django 4.0.4 on 2023-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_type', '0011_alter_projecttype_template_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='template_a',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='project_type_upload/'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='template_b',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='project_type_upload/'),
        ),
    ]
