# Generated by Django 4.0.4 on 2023-02-22 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppid', models.CharField(db_index=True, max_length=90, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1000, null=True)),
                ('address', models.CharField(db_index=True, max_length=1000, null=True, verbose_name='Street')),
                ('city', models.CharField(db_index=True, max_length=90, null=True)),
                ('state_short', models.CharField(max_length=60, null=True)),
                ('state', models.CharField(db_index=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('account_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('opportunity_package', models.CharField(max_length=100, null=True)),
                ('plan_drawings', models.CharField(max_length=10485760, null=True, verbose_name='Plans/Drawings')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created date')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('when_c', models.CharField(max_length=10485760, null=True)),
                ('bid_due_date', models.DateField(null=True, verbose_name='Pre construction bid due date')),
                ('units', models.CharField(max_length=100, null=True, verbose_name='Number of rooms/Units')),
                ('sf_size', models.IntegerField(db_index=True, default=0, null=True, verbose_name='Sq Ft')),
                ('stage_name', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Phase')),
                ('project_type', models.CharField(max_length=1000, null=True)),
                ('send_partner_details', models.CharField(max_length=1000, null=True)),
                ('close_date', models.CharField(max_length=20, null=True)),
                ('pipdcmkr_approval', models.CharField(max_length=10485760, null=True)),
                ('account_formula_name', models.CharField(max_length=1000, null=True)),
                ('account_billing_address', models.CharField(max_length=1000, null=True)),
                ('account_phone', models.CharField(max_length=90, null=True)),
                ('account_website', models.CharField(max_length=1000, null=True)),
                ('account_prequalification_application', models.CharField(max_length=10485760, null=True)),
                ('account_linkedin', models.CharField(max_length=1000, null=True)),
                ('account_facebook', models.CharField(max_length=1000, null=True)),
                ('account_twitter', models.CharField(max_length=1000, null=True)),
                ('status_update_1', models.CharField(db_index=True, max_length=10485760, null=True)),
                ('status_update_1_date', models.CharField(max_length=90, null=True)),
                ('status_update_2', models.CharField(db_index=True, max_length=10485760, null=True)),
                ('status_update_2_date', models.CharField(max_length=90, null=True)),
                ('status_update_3', models.CharField(db_index=True, max_length=10485760, null=True)),
                ('status_update_3_date', models.CharField(max_length=90, null=True)),
                ('status_update_4', models.CharField(db_index=True, max_length=10485760, null=True)),
                ('status_update_4_date', models.CharField(max_length=90, null=True)),
                ('status_update_5', models.CharField(db_index=True, max_length=10485760, null=True)),
                ('status_update_5_date', models.CharField(max_length=90, null=True)),
                ('last_modified_date_simple', models.CharField(max_length=90, null=True)),
                ('hot_lead_trade_scope', models.CharField(max_length=300, null=True)),
                ('negative_scope', models.CharField(max_length=300, null=True)),
                ('url_slug', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('country', models.CharField(max_length=3000, null=True)),
                ('company_account_id', models.CharField(max_length=100, null=True)),
                ('project_completion', models.DateField(null=True, verbose_name='Project Completion')),
                ('status', models.CharField(choices=[('A', 'Active'), ('NA', 'Not Active')], db_index=True, max_length=10)),
                ('laborer_union', models.BooleanField(null=True)),
                ('davis_bacon_prevailing_wage_detail', models.TextField(null=True)),
                ('primary_contact_name', models.CharField(max_length=100, null=True, verbose_name='Primary Contact Name')),
                ('primary_contact_phone', models.CharField(max_length=100, null=True, verbose_name='Primary Contact Phone')),
                ('primary_contact_email', models.CharField(max_length=100, null=True, verbose_name='Primary Contact Email')),
                ('site_contact_name', models.CharField(max_length=100, null=True, verbose_name='Site Contact Name')),
                ('site_contact_phone', models.CharField(max_length=100, null=True, verbose_name='Site Contact Phone')),
                ('site_contact_email', models.CharField(max_length=100, null=True, verbose_name='Site Contact Email')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('pq_score', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('project_quality_tier', models.CharField(max_length=100, null=True)),
                ('est_break_ground_date', models.DateField(null=True, verbose_name='Est. Break Ground Date')),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
