# Generated by Django 4.0.4 on 2023-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_companyaccount_emailtemplate_contactrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.CharField(max_length=20, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
