# Generated by Django 4.0.4 on 2023-03-08 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=3000, null=True)),
                ('email_type', models.CharField(choices=[('GC', 'General Contractor'), ('PB', 'Project Board')], max_length=2, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('subject', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('is_mass_email', models.BooleanField(default=False, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.companyaccount')),
                ('company_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.contact')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.contactrole')),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='projects.opportunity')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='projects.emailtemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_sent'],
                'get_latest_by': 'time_sent',
            },
        ),
    ]
