# Generated by Django 4.0.4 on 2023-03-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_useremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
