# Generated by Django 4.0.4 on 2023-07-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='market_working_region',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
