# Generated by Django 4.0.4 on 2023-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_planroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
