# Generated by Django 4.0.4 on 2023-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_delete_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
