# Generated by Django 4.0.4 on 2023-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontractor',
            name='company_slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
