# Generated by Django 4.0.4 on 2023-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0002_generalcontractor_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontractor',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
