# Generated by Django 4.0.4 on 2023-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0004_generalcontractor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontractor',
            name='is_public',
            field=models.BooleanField(default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='company_slug',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
