# Generated by Django 4.0.4 on 2023-09-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0005_generalcontractor_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontractor',
            name='facebook_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='instagram_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_add_itbs',
            field=models.BooleanField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_davis_bacon',
            field=models.BooleanField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_talent_request',
            field=models.BooleanField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_union',
            field=models.BooleanField(default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='linkedin_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='twitter_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='website_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='youtube_img_url',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
