# Generated by Django 4.0.4 on 2023-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0010_alter_generalcontractor_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontractor',
            name='facebook',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='instagram',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='plan_room_img_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='plan_room_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='pre_qualification_img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='pre_qualification_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='twitter',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontractor',
            name='youtube',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
