# Generated by Django 4.0.4 on 2023-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0011_alter_generalcontractor_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontractor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_annual_event',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_diversity_certification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_diversity_champion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_diversity_inclusion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_diversity_initiative',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_headhunter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_increase_supplier_network',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_share_more',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='is_workforce_inclusion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='num_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
