# Generated by Django 4.0.4 on 2023-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_planify', '0012_generalcontractor_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcontractor',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.AddField(
            model_name='generalcontractor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
